config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  resources :categories, only: [:index, :new, :create, :show]
  resources :users, only: [:new, :create, :edit, :update, :show]
root 'posts#index'

get '/register', to: 'users#new'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
get '/logout', to: 'sessions#destroy'

end

app/models/categories_post.rb
class CategoriesPost < ActiveRecord::Base
	belongs_to :post
	belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :categories_posts
	has_many :posts, through: :categories_posts

	validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	validates :content, presence: true, length: {minimum:3}
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	has_many :categories_posts
	has_many :categories, through: :categories_posts
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
	has_secure_password validations:false

	validates :name, presence: true, uniqueness: true
	validates :password, presence: true, on: :create, length:{minimum: 5} 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all
	end
	def new
		@categories = Category.all
		@category = Category.new
	end
	def create
		@category = Category.new(category_params)

		if @category.save!
			redirect_to categories_path
		else
			render :new
		end
	end

	def show
		@category = Category.find(params[:id])
	end
	
	private

	def category_params
		params.require(:category).permit(:name)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.build(params.require(:comment).permit(:content))
		@comment.user = current_user
		
		if @comment.save
			redirect_to post_path(@post)
		else
			render 'posts/show'
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
    @users = User.all

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.order("created_at DESC")
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.user = current_user
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, category_ids: [])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    #登入頁面使用
  end

  def create
    #尋找使用者
    user = User.find_by(name: params[:name])   
    #驗證使用者，若成功，就建立一個 session，把 user_id 放入 session hash
    if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        flash[:notice] = "You've logged in!"
        redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy 
    #登出畫面使用，刪除 session hash 裡面的 user_id
    session[:user_id] = nil
    flash[:notice] = "You've logged out!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			redirect_to login_path
		else
			render :new
		end
	end

	def show
		@user = current_user
		@posts = @user.posts.order("created_at DESC")
		@comments = @user.comments.order("created_at DESC")
	end

	private

		def user_params
			params.require(:user).permit(:name, :password)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sesson_helper.rb
module SessonHelper
end

app/views/categories/_category.html.erb
<!-- <span class="badge"><%= category.name %></span> -->
<span class="label label-info"><%= link_to "#{category.name}", category_path(category) %></span>

app/views/categories/index.html.erb
<%= render 'shared/title', title:'All Categories' %>
<div class="row">
	<div class="well col-md-8 col-md-offset-1">
	<bold> Current Categories </bold><br>
	<% @categories.each do |category| %>
		<span class="label label-primary"><%= category.name %>
		</span>
	<% end %>
	</div>

	<div class="col-md-8 col-md-offset-1">
	<span>
  <%= link_to "Add New Category", new_category_path %> |
  <%= link_to "Back to all posts", posts_path %>

  </span>
</div>

app/views/categories/new.html.erb
<%= render 'shared/title', title:'Add New Category' %>

<div class="row">
	<div class="col-md-8 col-md-offset-1">
		<%= form_for(@category) do |f| %>
		<div class="form-group">
   		<%= f.text_field :name, class:"col-sm-10" %>
  	</div>
  	<p>
		<div class="actions">
  		<button class="btn btn-primary" type="submit">
   Submit </button>
   	<% f.submit %>
   	</div></p>
  </div>
</div>
<% end %>
<br>
<div class="well col-md-8 col-md-offset-1">
	<bold> Current Categories </bold><br>
	<%= render partial:'category', collection: @categories %>
	</div>
</div>

app/views/categories/show.html.erb
<%= render 'shared/title', title: "Category : #{@category.name}" %>

<% @category.posts.each do |post| %>
<%= render 'posts/post', post: post %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
 			<%= link_to "Kitboard", root_path, :class => 'navbar-brand' %>
 		</div>
 	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav navbar-right">
			<% if logged_in? %>
				<li><%= link_to "Your Posts and Edit", user_path(current_user) %></li>
				<li><%= link_to 'New Post', new_post_path %></li>
				<li><%= link_to 'Logout', logout_path %></li>

			<% else %>
				<a href="/login" class="btn btn-default navbar-btn" role="button">Login</a>
				<li><%= link_to "Register", register_path %></li>

			<% end %>
	</ul>

	</div>
	</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kitboard2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<%= render 'layouts/navigation' %>
	</header>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
<div class="col-md-12">
  <div class="field">

    <%= f.label :title %><br>
    <%= f.text_field :title, class:"col-md-12" %>
    <%= f.label :content %><br>
    <%= f.text_area :content, rows:10, class:"col-md-12" %>
    Category: 
    <%= collection_check_boxes(:post, :category_ids, Category.all, :id, :name) do |c| %>
    <%= c.label(class:"checkbox_inline"){c.check_box(class:"checkbox")} + c.text %>
    
    <% end %>
   | <%= link_to 'Add', new_category_path, :target => "_blank" %>
  </div>


  <div class="actions">
  <button class="btn btn-primary" type="submit">
   Submit </button>
   <% f.submit %>
  </div>
</div>
</div>

<% end %>

app/views/posts/_post.html.erb
<div class="row">
  <div class="well col-md-8 col-md-offset-1">

    <div class="panel panel-primary">
      <div class="panel-heading">
      <h3 class="panel-title"><%= post.title %></h3>
      </div>
      <div class="panel-body">
      <h3><%= post.content %></h3>
      <br>
      <span>
      <%= link_to "Show post", post_path(post) %> |
      <%= render partial: 'categories/category', collection: post.categories %>
      </span>

      <br>
      <small><%= "#{post.created_at.to_date}" %> </small>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/title', title:'Editing Post' %>

<div class="row">
  <div class="col-md-8 col-md-offset-1">
<%= render 'form' %>
<span>
<%= link_to "Back to post", post_path(@post) %> 
</span>
<br>
</div>

app/views/posts/index.html.erb
<%= render 'shared/title', title:'All Posts' %>
<% @posts.each do |post| %>

  <%= render 'post', post: post %>

<% end %>

app/views/posts/new.html.erb
<%= render 'shared/title', title:'Add New Post' %>

<div class="row">
  <div class="well col-md-8 col-md-offset-1">
	<%= render 'form' %>

	<%= link_to 'Back', posts_path %>
	</div>
</div>

app/views/posts/show.html.erb
<%= render 'shared/title', title:'Show Post' %>

<div class="row">
  <div class="well col-md-8 col-md-offset-1">
    <div class="panel panel-primary">
      <div class="panel-heading">
      	<h3 class="panel-title"><%= @post.title %></h3>
    	</div>
    	<div class="panel-body"> 
      <p><%= render partial: 'categories/category', collection: @post.categories %></p>
      <h3><%= @post.content %></h3>
      <br>
  
  		Posted by:
  		<%= @post.user.name if @post.user_id %>
      <br>
      <small><%= @post.created_at.to_date %> </small>
      <br>

    	</div>
  	</div>
</div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-1">
  <h3>All comments: </h3>

  		<% @post.comments.each do |comment| %>
    	<li><strong>"<%= comment.content %>"</strong>
    	from: <%= comment.user.name if comment.user_id %></li>
    	<br>
    	<% end %>
	</div>
</div>

<div class="row">
  <div class="well col-md-6 col-md-offset-1">
    <% if logged_in? %>
      <h4> Leave a comment </h4>
		  <%= form_for [@post, @comment] do |f| %>
      <%= f.text_area :content, class: 'col-md-12' %>
  	   <span><br>
  	 <div class="actions">
  	   <button class="btn btn-primary" type="submit">
   Submit </button>
    <% f.submit %>
  	 </div>
      <% end %>
      <% else %>
      <h4> Log in to leave a comment.</h4>
      <%= link_to 'Log in here', login_path %> |
    <% end %>

		<%= link_to 'Back to all posts', posts_path %>
		</span>
	</div>
</div>

app/views/shared/_title.html.erb
<div class="row">
  <div class="col-md-offset-1">
<div class="page-header">
  <h1><%= title %></h1>
</div>
</div>

app/views/users/new.html.erb
<%= render '/shared/title', title: 'Register'%>
	<div class="well col-md-8 col-md-offset-1">
		<%= form_for @user do |f| %>
		<div class="form-group">
		<%= f.label :name %>
		<br>
		<%= f.text_field :name, :placeholder => "Your Name", class:"col-md-12" %>
		</div><br>
			<div class="form-group">
			<%= f.label :Password %>
      <br>
      <%= f.password_field :password, :placeholder =>"Set 5 digits", class:"col-md-12" %>
      </div>
      <br>
      <%= f.submit(@user.new_record? ? 'Register' : 'Update Profile', class: 'btn btn-primary') %>
    </div>
		<% end %>
	</div>

app/views/users/show.html.erb
<%= render '/shared/title', title: "Hello! #{current_user.name}" %>

<div class="row">
	<div class="col-md-8 col-md-offset-1">
	<h3> Your posts: </h3>
		<% if @posts.present? %>
  		<% @posts.each do |post| %>
			<li><%= link_to "#{post.title}", post_path(post) %>
      	<%= link_to '(Edit Post)', edit_post_path(post) %>
      	<small><%= "- #{post.created_at.to_date}" %></small>
      </li>
			
  	<% end %>
		<% else %>
    <p> You don't have any post yet. Keep posting! </p>
		<% end %>
	</div>
</div>

<div class="row">
	<div class="col-md-8 col-md-offset-1">
		<h3> Your comments: </h3>
			<% if @comments.present? %>
				<% @comments.each do |comment| %>
 		<li><%= link_to "#{comment.content}", post_path(comment.post) %>
 		<small><%= "- #{comment.created_at.to_date}" %></small></li>
 		<% end %>
 		<% else %>
 		<p> You don't have any comment yet. Tell them what you think! </p>
 		<% end %>
 	</div>
</div>